name = "VibrationData"
uuid = "85cedecc-ec67-4717-8ef3-ce3f1b8dc459"
authors = ["Mathieu Aucejo <79322171+maucejo@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
LazyGrids = "7031d0ef-c40d-4431-b2f8-61a8d2f650db"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
DSP = "0.8.0"
FiniteDiff = "2.26.2"
TestItemRunner = "1.0.5"
TestItems = "1.0.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
